[env]
RUST_MIN_STACK = "8192000"

[alias]
b = "build"
f = "fmt --check"
ff = "fmt"
l = "clippy --features=test,test-bpf"
lf = "clippy --features=test,test-bpf --fix"
t = "test --manifest-path ./Cargo.toml --features test-bpf --target x86_64-apple-darwin --features=test,test-bpf"
r = "run"
